export const AnalysisErrorCode = {
  USAGE_LIMIT_EXCEEDED: 'USAGE_LIMIT_EXCEEDED',
  AI_SERVICE_ERROR: 'AI_SERVICE_ERROR',
  API_QUOTA_EXCEEDED: 'API_QUOTA_EXCEEDED',
  SUBSCRIPTION_EXPIRED: 'SUBSCRIPTION_EXPIRED',
  INVALID_INPUT: 'INVALID_INPUT',
  DATABASE_ERROR: 'DATABASE_ERROR',
  USER_NOT_FOUND: 'USER_NOT_FOUND',
  SUBSCRIPTION_NOT_FOUND: 'SUBSCRIPTION_NOT_FOUND',
  ANALYSIS_NOT_FOUND: 'ANALYSIS_NOT_FOUND',
  ANALYSIS_FORBIDDEN: 'ANALYSIS_FORBIDDEN',
  ANALYSIS_DATA_CORRUPTED: 'ANALYSIS_DATA_CORRUPTED',
} as const;

export type AnalysisErrorCode =
  (typeof AnalysisErrorCode)[keyof typeof AnalysisErrorCode];

export type AnalysisServiceError = AnalysisErrorCode;
